test.yml upadted

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -21,47 +21,47 @@ jobs:
           TELEGRAM_TOPIC: ${{ secrets.TELEGRAM_TOPIC }}
         with:
           status: ${{job.status}}
-  fail:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - name: Run fail
-        run: exit 1
-      - name: Send message to Telegram
-        uses: ./
-        if: always()
-        env:
-          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
-          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
-          TELEGRAM_TOPIC: ${{ secrets.TELEGRAM_TOPIC }}
-        with:
-          status: ${{job.status}}
-  no-status:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - name: Run success
-        run: exit 0
-      - name: Send message to Telegram
-        uses: ./
-        if: always()
-        env:
-          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
-          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
-          TELEGRAM_TOPIC: ${{ secrets.TELEGRAM_TOPIC }}
-  alternative-template:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - name: Run success
-        run: exit 0
-      - name: Send message to Telegram
-        uses: ./
-        if: always()
-        env:
-          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
-          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
-          TELEGRAM_TOPIC: ${{ secrets.TELEGRAM_TOPIC }}
-        with:
-          commit_template: ./templates/commit-alternative.mustache
-          status: ${{job.status}}
+  # fail:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: Run fail
+  #       run: exit 1
+  #     - name: Send message to Telegram
+  #       uses: ./
+  #       if: always()
+  #       env:
+  #         TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
+  #         TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
+  #         TELEGRAM_TOPIC: ${{ secrets.TELEGRAM_TOPIC }}
+  #       with:
+  #         status: ${{job.status}}
+  # no-status:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: Run success
+  #       run: exit 0
+  #     - name: Send message to Telegram
+  #       uses: ./
+  #       if: always()
+  #       env:
+  #         TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
+  #         TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
+  #         TELEGRAM_TOPIC: ${{ secrets.TELEGRAM_TOPIC }}
+  # alternative-template:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: Run success
+  #       run: exit 0
+  #     - name: Send message to Telegram
+  #       uses: ./
+  #       if: always()
+  #       env:
+  #         TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
+  #         TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
+  #         TELEGRAM_TOPIC: ${{ secrets.TELEGRAM_TOPIC }}
+  #       with:
+  #         commit_template: ./templates/commit-alternative.mustache
+  #         status: ${{job.status}}
